name: pa11y tests
on: [pull_request]

jobs:
  build:
    name: Building site and running pa11y-ci tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install pa11y-ci dependencies.
        working-directory: a11y
        run: npm install

      - name: Run pa11y-ci.
        working-directory: a11y
        run: npm run pa11y-ci 2>&1 | tee pa11y_output.txt

      - name: Read pa11y_output file.
        id: pa11y_output
        uses: juliangruber/read-file-action@v1
        with:
          path: a11y/pa11y_output.txt

      - name: Comment on pull request.
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({ 
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ```${{ steps.pa11y_output.outputs.content }}```
            })

      - name: Check for pa11y failures.
        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
        run: |
          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
          exit 1

      - name: View context attributes
        uses: actions/github-script@v3
        with:
          script: console.log(context)
