name: Run Cypress Test
description: A simple Cypress GH Action
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - name: Checkout
      uses: actions/checkout@v2

      - name Cypress tests
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
          working-directory: cypress/integration
          build: npx cypress info
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
