name: Run Cypress Test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    container: cypress/browsers:node12.13.0-chrome78-ff70
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: cypress-io/github-action@v2
        id: cypress
        continue-on-error: true
        with:
          working-directory: tests
          record: true
          parallel: true
          group: Recordings
          tag: action
          build: npx cypress info
          run: npx cypress run --record --key eb660742-e519-4474-8c34-24149f3dca2a
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Dashboard URL
        run: |
          echo Cypress finished with: ${{ steps.cypress.outcome }}
          echo See results at ${{ steps.cypress.outputs.dashboardUrl }}
